[website]
base_url = 'https://accord.kineoadapt.com/#user/login'

[credentials]
username = 'nwo@anthillagency.com'
password = 'Oncodemia1234'

[playwright]
timeout = 30_000  # ms
headless = false  # set false to see how browser works